[project]
name = "demo-fast-api"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Prasanna", email = "prasannavenkatesh.m@arisecapital.in" }
]
requires-python = ">=3.14"
dependencies = [
    "fastapi>=0.141.1",
    "pinecone>=10.0.0",
    "pyjwt>=2.14.0",
    "pypdf>=6.19.0",
    "python-docx>=1.2.0",
    "python-dotenv>=1.2.3",
    "python-multipart>=0.0.32",
    "sentence-transformers>=6.1.0",
    "uvicorn>=0.53.0",
]

[project.scripts]
demo-fast-api = "demo_fast_api:main"

[build-system]
requires = ["uv_build>=0.12.16,<0.13.0"]
build-backend = "uv_build"
